vid_properties = { floating = true,
                   border_width = 0,
                   sticky = true,
                   focus = true,
                   tag = tags[screen.count()][1],
                   ontop = true,
                 }
awful.rules.rules = {
    -- All clients will match this rule.
    { rule = { },
      properties = { border_width = beautiful.border_width,
                     border_color = beautiful.border_normal,
                     keys = clientkeys,
                     buttons = clientbuttons,
                     size_hints_honor = false,
                   },
    },
    { rule = {}, callback = awful.client.setslave },
    { rule = { class = "Tilda" ,
               name = "tilda" },
      properties = { floating = true,
                     size_hints_honor = true,
                     size_hints = {
                                    user_position = false,
                                    user_size = false,
                                    program_position = true,
                                    program_size = true
                                  },
                     border_width = 0,
                   }, },
    { rule = { class = "mplayer2" },
      properties = awful.util.table.join(vid_properties,
                                         { size_hints_honor = true }),
      },
    { rule = { class = "gimp" },
      properties = { floating = true,
                     tag = tags[1][5] } },
    { rule = { class = "Chromium-browser" },
      properties = { tag = tags[1][2] } },
    { rule = { class = "Liferea" },
      properties = { tag = tags[1][3] } },
    { rule = { class = "Pidgin" },
      properties = { tag = tags[1][1] } },
    { rule = { class = "feh" },
      properties = { floating = true } },
    { rule = { class = "Wine",
               instance = "explorer.exe" },
      properties = { floating = true,
                     size_hints_honor = true,
                     border_width = 0,
                     ontop = true
                   },
    },
    { rule = { class = "Skype" },
      properties = { floating = true, } },
    { rule = { class = "Huludesktop.bin" },
      properties = vid_properties, },
}
