require('widgets.battery')
require('widgets.cpu')
require('widgets.disk')
require('widgets.memory')
require('widgets.mpd')
require('widgets.net')
require('widgets.randr')
require('widgets.volume')

module('widgets')
