# zsh zshenv

# Set PATH/path to be unique, then add ~/bin
typeset -U path
path+=( ~/bin )

export http_proxy='http://localhost:8118'
export HTTP_PROXY="$http_proxy"

export MPD_HOST="$(< ${XDG_CONFIG_HOME:-~/.config}/sekrit/mpd_pass)@deskbert"

ZDOTDIR=${XDG_CONFIG_HOME:-~/.config}/zsh
